"""
Step 8B — Citation Validator

Validates citations generated by the LLM against the actual
retrieved evidence.

Checks:
1. Citation syntax
2. Citation existence
3. Citation belongs to retrieved evidence
4. Citation coverage
5. Unsupported citations
6. Missing citations

Expected citation format:

[SOURCE: RET-002-P01-C001]

The validator does NOT determine whether the LLM's factual
statement is semantically correct. It verifies that cited
sources exist and were actually supplied as evidence.
"""

import re
from typing import Any, Dict, List, Set


class CitationValidator:

    CITATION_PATTERN = re.compile(
        r"\[SOURCE:\s*([A-Za-z0-9_-]+)\]"
    )

    def __init__(self):

        print("Citation Validator ready.")

    # ==================================================================
    # Extract citations
    # ==================================================================

    def extract_citations(
        self,
        answer: str,
    ) -> List[str]:
        """
        Extract citations from an answer.

        Example:

        [SOURCE: RET-001-P01-C001]

        returns:

        ["RET-001-P01-C001"]
        """

        if not answer:
            return []

        citations = self.CITATION_PATTERN.findall(
            answer
        )

        # Preserve order while removing duplicates
        unique = []

        seen = set()

        for citation in citations:

            if citation not in seen:

                seen.add(citation)

                unique.append(citation)

        return unique

    # ==================================================================
    # Build evidence map
    # ==================================================================

    @staticmethod
    def build_evidence_map(
        evidence: List[Dict[str, Any]],
    ) -> Dict[str, Dict[str, Any]]:
        """
        Create:

        chunk_id -> evidence metadata
        """

        evidence_map = {}

        for item in evidence:

            chunk_id = item.get("chunk_id")

            if not chunk_id:
                continue

            evidence_map[chunk_id] = item

        return evidence_map

    # ==================================================================
    # Validate citations
    # ==================================================================

    def validate(
        self,
        answer: str,
        evidence: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Validate generated citations.

        Returns:

        {
            "valid": True/False,
            "citations": [...],
            "valid_citations": [...],
            "invalid_citations": [...],
            "missing_citations": [...],
            "citation_count": ...,
            "valid_citation_count": ...,
            "coverage": ...,
            "issues": [...]
        }
        """

        if not answer:

            return {
                "valid": False,
                "citations": [],
                "valid_citations": [],
                "invalid_citations": [],
                "missing_citations": [],
                "citation_count": 0,
                "valid_citation_count": 0,
                "coverage": 0.0,
                "issues": [
                    "Generated answer is empty."
                ],
            }

        evidence_map = self.build_evidence_map(
            evidence
        )

        retrieved_chunk_ids = set(
            evidence_map.keys()
        )

        citations = self.extract_citations(
            answer
        )

        citation_set = set(citations)

        # --------------------------------------------------------------
        # Valid citations
        # --------------------------------------------------------------

        valid_citations = [
            citation
            for citation in citations
            if citation in retrieved_chunk_ids
        ]

        # --------------------------------------------------------------
        # Invalid citations
        # --------------------------------------------------------------

        invalid_citations = [
            citation
            for citation in citations
            if citation not in retrieved_chunk_ids
        ]

        # --------------------------------------------------------------
        # Evidence that was never cited
        # --------------------------------------------------------------

        missing_citations = [
            chunk_id
            for chunk_id in retrieved_chunk_ids
            if chunk_id not in citation_set
        ]

        # --------------------------------------------------------------
        # Calculate citation coverage
        # --------------------------------------------------------------

        if retrieved_chunk_ids:

            coverage = (
                len(valid_citations)
                / len(retrieved_chunk_ids)
            )

        else:

            coverage = 0.0

        # --------------------------------------------------------------
        # Issues
        # --------------------------------------------------------------

        issues = []

        if not citations:

            issues.append(
                "No source citations were found in the answer."
            )

        if invalid_citations:

            issues.append(
                "The answer contains citations that were not "
                "present in the retrieved evidence."
            )

        # We don't automatically fail because every retrieved chunk
        # does not need to be cited.
        #
        # For example, retrieval may provide 6 chunks but the answer
        # may legitimately need only 2 of them.

        # --------------------------------------------------------------
        # Overall validity
        # --------------------------------------------------------------

        valid = (
            len(citations) > 0
            and len(invalid_citations) == 0
        )

        return {
            "valid": valid,
            "citations": citations,
            "valid_citations": valid_citations,
            "invalid_citations": invalid_citations,
            "missing_citations": missing_citations,
            "citation_count": len(citations),
            "valid_citation_count": len(valid_citations),
            "coverage": round(
                coverage,
                4,
            ),
            "issues": issues,
        }

    # ==================================================================
    # Validate individual citation
    # ==================================================================

    def validate_citation(
        self,
        citation: str,
        evidence: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Validate one citation.
        """

        evidence_map = self.build_evidence_map(
            evidence
        )

        exists = citation in evidence_map

        return {
            "citation": citation,
            "valid": exists,
            "evidence": (
                evidence_map.get(citation)
                if exists
                else None
            ),
        }

    # ==================================================================
    # Annotate citations
    # ==================================================================

    def annotate_answer(
        self,
        answer: str,
        validation: Dict[str, Any],
    ) -> str:
        """
        Add a simple validation note to invalid citations.

        This does not modify valid citations.

        Example:

        [SOURCE: FAKE-001]
        becomes:

        [SOURCE: FAKE-001] ⚠ INVALID SOURCE
        """

        invalid = set(
            validation.get(
                "invalid_citations",
                [],
            )
        )

        if not invalid:
            return answer

        annotated = answer

        for citation in invalid:

            replacement = (
                f"[SOURCE: {citation}] "
                "[INVALID SOURCE]"
            )

            annotated = annotated.replace(
                f"[SOURCE: {citation}]",
                replacement,
            )

        return annotated

    # ==================================================================
    # Report
    # ==================================================================

    @staticmethod
    def print_report(
        validation: Dict[str, Any]
    ):

        print("\n")
        print("=" * 80)
        print("CITATION VALIDATION REPORT")
        print("=" * 80)

        print(
            "\nValid:",
            validation["valid"],
        )

        print(
            "Citation count:",
            validation["citation_count"],
        )

        print(
            "Valid citation count:",
            validation["valid_citation_count"],
        )

        print(
            "Coverage:",
            f"{validation['coverage'] * 100:.1f}%",
        )

        print("\nCitations:")

        for citation in validation["citations"]:

            print(
                f"  - {citation}"
            )

        if validation["invalid_citations"]:

            print("\nINVALID CITATIONS:")

            for citation in validation[
                "invalid_citations"
            ]:

                print(
                    f"  - {citation}"
                )

        if validation["missing_citations"]:

            print(
                "\nRetrieved evidence not cited:"
            )

            for citation in validation[
                "missing_citations"
            ]:

                print(
                    f"  - {citation}"
                )

        if validation["issues"]:

            print("\nISSUES:")

            for issue in validation["issues"]:

                print(
                    f"  - {issue}"
                )

        print("\n" + "=" * 80)


# ======================================================================
# Standalone test
# ======================================================================

if __name__ == "__main__":

    print("=" * 80)
    print("STEP 8B — CITATION VALIDATOR TEST")
    print("=" * 80)

    validator = CitationValidator()

    # --------------------------------------------------------------
    # Fake retrieved evidence
    # --------------------------------------------------------------

    evidence = [

        {
            "chunk_id": "REF-002-P01-C001",
            "document_id": "REF-002",
            "file_name": "refund_timelines.pdf",
            "domain": "refunds",
            "page": 1,
            "text": (
                "Daraz Wallet credit usually takes "
                "24-48 hours after refund approval."
            ),
        },

        {
            "chunk_id": "REF-002-P01-C002",
            "document_id": "REF-002",
            "file_name": "refund_timelines.pdf",
            "domain": "refunds",
            "page": 1,
            "text": (
                "Bank processing times can affect refund speed."
            ),
        },

    ]

    # --------------------------------------------------------------
    # Test 1 — Valid answer
    # --------------------------------------------------------------

    answer_1 = """
Refunds to the Daraz Wallet usually take 24-48 hours
after approval. [SOURCE: REF-002-P01-C001]

Bank processing times can also affect the overall refund speed.
[SOURCE: REF-002-P01-C002]
"""

    print("\n")
    print("-" * 80)
    print("TEST 1 — VALID CITATIONS")
    print("-" * 80)

    result_1 = validator.validate(
        answer=answer_1,
        evidence=evidence,
    )

    validator.print_report(result_1)

    # --------------------------------------------------------------
    # Test 2 — Invalid citation
    # --------------------------------------------------------------

    answer_2 = """
Refunds usually take 24-48 hours.
[SOURCE: REF-002-P01-C001]

The refund can also be completed immediately in every case.
[SOURCE: FAKE-999]
"""

    print("\n")
    print("-" * 80)
    print("TEST 2 — INVALID CITATION")
    print("-" * 80)

    result_2 = validator.validate(
        answer=answer_2,
        evidence=evidence,
    )

    validator.print_report(result_2)

    # --------------------------------------------------------------
    # Test 3 — No citations
    # --------------------------------------------------------------

    answer_3 = """
Refund timing depends on the payment method.
"""

    print("\n")
    print("-" * 80)
    print("TEST 3 — NO CITATIONS")
    print("-" * 80)

    result_3 = validator.validate(
        answer=answer_3,
        evidence=evidence,
    )

    validator.print_report(result_3)

    # --------------------------------------------------------------
    # Final
    # --------------------------------------------------------------

    print("\n")
    print("=" * 80)
    print("STEP 8B TEST COMPLETE")
    print("=" * 80)