"""
Step 8B — Citation Validator

Validates citations generated by the LLM against the actual
retrieved evidence.

Supported citation formats:

    [SOURCE: REF-002-P01-C001]

and:

    【REF-002-P01-C001】

The validator checks:

1. Citation syntax
2. Citation existence
3. Citation belongs to retrieved evidence
4. Citation coverage
5. Unsupported citations
6. Missing citations

The validator does NOT determine whether an answer is
semantically correct. It verifies that cited sources exist
and were actually supplied as evidence.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List


class CitationValidator:

    # --------------------------------------------------------------
    # Supported citation formats
    # --------------------------------------------------------------

    SOURCE_CITATION_PATTERN = re.compile(
        r"\[SOURCE:\s*([A-Za-z0-9_-]+)\]"
    )

    BRACKET_CITATION_PATTERN = re.compile(
        r"【\s*([A-Za-z0-9_-]+)\s*】"
    )

    # --------------------------------------------------------------
    # Initialization
    # --------------------------------------------------------------

    def __init__(self):

        print("Citation Validator ready.")

    # ==============================================================
    # Extract citations
    # ==============================================================

    def extract_citations(
        self,
        answer: str,
    ) -> List[str]:
        """
        Extract citations from the generated answer.

        Supports:

            [SOURCE: REF-002-P01-C001]

        and:

            【REF-002-P01-C001】

        Returns unique citations while preserving order.
        """

        if not answer:
            return []

        citations = []

        # ----------------------------------------------------------
        # Format 1:
        # [SOURCE: REF-002-P01-C001]
        # ----------------------------------------------------------

        citations.extend(
            self.SOURCE_CITATION_PATTERN.findall(
                answer
            )
        )

        # ----------------------------------------------------------
        # Format 2:
        # 【REF-002-P01-C001】
        # ----------------------------------------------------------

        citations.extend(
            self.BRACKET_CITATION_PATTERN.findall(
                answer
            )
        )

        # ----------------------------------------------------------
        # Preserve order and remove duplicates
        # ----------------------------------------------------------

        unique = []

        seen = set()

        for citation in citations:

            if citation not in seen:

                seen.add(citation)

                unique.append(citation)

        return unique

    # ==============================================================
    # Build evidence map
    # ==============================================================

    @staticmethod
    def build_evidence_map(
        evidence: List[Dict[str, Any]],
    ) -> Dict[str, Dict[str, Any]]:
        """
        Create:

            chunk_id -> evidence metadata
        """

        evidence_map = {}

        for item in evidence:

            if not isinstance(item, dict):
                continue

            chunk_id = item.get(
                "chunk_id"
            )

            if not chunk_id:
                continue

            evidence_map[chunk_id] = item

        return evidence_map

    # ==============================================================
    # Validate citations
    # ==============================================================

    def validate(
        self,
        answer: str,
        evidence: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Validate generated citations.

        Returns:

        {
            "valid": True/False,
            "citations": [...],
            "valid_citations": [...],
            "invalid_citations": [...],
            "missing_citations": [...],
            "citation_count": ...,
            "valid_citation_count": ...,
            "coverage": ...,
            "issues": [...]
        }
        """

        # ----------------------------------------------------------
        # Empty answer
        # ----------------------------------------------------------

        if not answer:

            return {
                "valid": False,
                "citations": [],
                "valid_citations": [],
                "invalid_citations": [],
                "missing_citations": [],
                "citation_count": 0,
                "valid_citation_count": 0,
                "coverage": 0.0,
                "issues": [
                    "Generated answer is empty."
                ],
            }

        # ----------------------------------------------------------
        # Evidence map
        # ----------------------------------------------------------

        evidence_map = self.build_evidence_map(
            evidence
        )

        retrieved_chunk_ids = set(
            evidence_map.keys()
        )

        # ----------------------------------------------------------
        # Extract citations
        # ----------------------------------------------------------

        citations = self.extract_citations(
            answer
        )

        citation_set = set(
            citations
        )

        # ----------------------------------------------------------
        # Valid citations
        # ----------------------------------------------------------

        valid_citations = [
            citation
            for citation in citations
            if citation in retrieved_chunk_ids
        ]

        # ----------------------------------------------------------
        # Invalid citations
        # ----------------------------------------------------------

        invalid_citations = [
            citation
            for citation in citations
            if citation not in retrieved_chunk_ids
        ]

        # ----------------------------------------------------------
        # Evidence not cited
        # ----------------------------------------------------------

        missing_citations = [
            chunk_id
            for chunk_id in retrieved_chunk_ids
            if chunk_id not in citation_set
        ]

        # ----------------------------------------------------------
        # Coverage
        #
        # Stored as a ratio:
        #
        # 2 / 4 = 0.5
        #
        # The Streamlit UI converts this to 50%.
        # ----------------------------------------------------------

        if retrieved_chunk_ids:

            coverage = (
                len(valid_citations)
                / len(retrieved_chunk_ids)
            )

        else:

            coverage = 0.0

        # ----------------------------------------------------------
        # Issues
        # ----------------------------------------------------------

        issues = []

        if not citations:

            issues.append(
                "No source citations were found in the answer."
            )

        if invalid_citations:

            issues.append(
                "The answer contains citations that were not "
                "present in the retrieved evidence."
            )

        # ----------------------------------------------------------
        # Overall validity
        #
        # A response is citation-valid when:
        #
        # 1. At least one citation exists.
        # 2. Every citation belongs to retrieved evidence.
        #
        # It is NOT required that every retrieved chunk be cited.
        # ----------------------------------------------------------

        valid = (
            len(citations) > 0
            and len(invalid_citations) == 0
        )

        return {

            "valid": valid,

            "citations": citations,

            "valid_citations": valid_citations,

            "invalid_citations": invalid_citations,

            "missing_citations": missing_citations,

            "citation_count": len(citations),

            "valid_citation_count": len(
                valid_citations
            ),

            "coverage": round(
                coverage,
                4,
            ),

            "issues": issues,
        }

    # ==============================================================
    # Validate individual citation
    # ==============================================================

    def validate_citation(
        self,
        citation: str,
        evidence: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Validate one citation.
        """

        evidence_map = self.build_evidence_map(
            evidence
        )

        exists = (
            citation in evidence_map
        )

        return {
            "citation": citation,
            "valid": exists,
            "evidence": (
                evidence_map.get(
                    citation
                )
                if exists
                else None
            ),
        }

    # ==============================================================
    # Annotate citations
    # ==============================================================

    def annotate_answer(
        self,
        answer: str,
        validation: Dict[str, Any],
    ) -> str:
        """
        Add INVALID SOURCE after citations that do not
        belong to the retrieved evidence.

        Supports both citation formats.
        """

        invalid = set(
            validation.get(
                "invalid_citations",
                [],
            )
        )

        if not invalid:
            return answer

        annotated = answer

        for citation in invalid:

            # ------------------------------------------------------
            # [SOURCE: ID]
            # ------------------------------------------------------

            source_format = (
                f"[SOURCE: {citation}]"
            )

            annotated = annotated.replace(
                source_format,
                f"{source_format} [INVALID SOURCE]",
            )

            # ------------------------------------------------------
            # 【ID】
            # ------------------------------------------------------

            bracket_format = (
                f"【{citation}】"
            )

            annotated = annotated.replace(
                bracket_format,
                f"{bracket_format} [INVALID SOURCE]",
            )

        return annotated

    # ==============================================================
    # Report
    # ==============================================================

    @staticmethod
    def print_report(
        validation: Dict[str, Any]
    ):

        print("\n")
        print("=" * 80)
        print("CITATION VALIDATION REPORT")
        print("=" * 80)

        print(
            "\nValid:",
            validation["valid"],
        )

        print(
            "Citation count:",
            validation["citation_count"],
        )

        print(
            "Valid citation count:",
            validation["valid_citation_count"],
        )

        print(
            "Coverage:",
            f"{validation['coverage'] * 100:.1f}%",
        )

        print("\nCitations:")

        for citation in validation[
            "citations"
        ]:

            print(
                f"  - {citation}"
            )

        if validation[
            "invalid_citations"
        ]:

            print(
                "\nINVALID CITATIONS:"
            )

            for citation in validation[
                "invalid_citations"
            ]:

                print(
                    f"  - {citation}"
                )

        if validation[
            "missing_citations"
        ]:

            print(
                "\nRetrieved evidence not cited:"
            )

            for citation in validation[
                "missing_citations"
            ]:

                print(
                    f"  - {citation}"
                )

        if validation["issues"]:

            print(
                "\nISSUES:"
            )

            for issue in validation[
                "issues"
            ]:

                print(
                    f"  - {issue}"
                )

        print(
            "\n" + "=" * 80
        )


# ==============================================================
# STANDALONE TEST
# ==============================================================

if __name__ == "__main__":

    print("=" * 80)
    print("STEP 8B — CITATION VALIDATOR TEST")
    print("=" * 80)

    validator = CitationValidator()

    # --------------------------------------------------------------
    # Fake evidence
    # --------------------------------------------------------------

    evidence = [

        {
            "chunk_id": "REF-002-P01-C001",
            "document_id": "REF-002",
            "file_name": "refund_timelines.pdf",
            "domain": "refunds",
            "page": 1,
            "text": (
                "Daraz Wallet credit usually takes "
                "24-48 hours after refund approval."
            ),
        },

        {
            "chunk_id": "REF-002-P01-C002",
            "document_id": "REF-002",
            "file_name": "refund_timelines.pdf",
            "domain": "refunds",
            "page": 1,
            "text": (
                "Bank processing times can affect refund speed."
            ),
        },
    ]

    # --------------------------------------------------------------
    # Test 1 — SOURCE format
    # --------------------------------------------------------------

    answer_1 = """
Refunds to the Daraz Wallet usually take 24-48 hours.
[SOURCE: REF-002-P01-C001]

Bank processing times can also affect refund speed.
[SOURCE: REF-002-P01-C002]
"""

    print("\n")
    print("-" * 80)
    print("TEST 1 — [SOURCE: ...] FORMAT")
    print("-" * 80)

    result_1 = validator.validate(
        answer=answer_1,
        evidence=evidence,
    )

    validator.print_report(
        result_1
    )

    # --------------------------------------------------------------
    # Test 2 — Bracket format
    # --------------------------------------------------------------

    answer_2 = """
Refunds to the Daraz Wallet usually take 24-48 hours.
【REF-002-P01-C001】

Bank processing times can affect refund speed.
【REF-002-P01-C002】
"""

    print("\n")
    print("-" * 80)
    print("TEST 2 — 【...】 FORMAT")
    print("-" * 80)

    result_2 = validator.validate(
        answer=answer_2,
        evidence=evidence,
    )

    validator.print_report(
        result_2
    )

    # --------------------------------------------------------------
    # Test 3 — Invalid citation
    # --------------------------------------------------------------

    answer_3 = """
Refunds usually take 24-48 hours.
【REF-002-P01-C001】

The refund is always completed immediately.
【FAKE-999】
"""

    print("\n")
    print("-" * 80)
    print("TEST 3 — INVALID CITATION")
    print("-" * 80)

    result_3 = validator.validate(
        answer=answer_3,
        evidence=evidence,
    )

    validator.print_report(
        result_3
    )

    # --------------------------------------------------------------
    # Test 4 — No citations
    # --------------------------------------------------------------

    answer_4 = """
Refund timing depends on the payment method.
"""

    print("\n")
    print("-" * 80)
    print("TEST 4 — NO CITATIONS")
    print("-" * 80)

    result_4 = validator.validate(
        answer=answer_4,
        evidence=evidence,
    )

    validator.print_report(
        result_4
    )

    # --------------------------------------------------------------
    # Final
    # --------------------------------------------------------------

    print("\n")
    print("=" * 80)
    print("STEP 8B TEST COMPLETE")
    print("=" * 80)